# Generated by Django 4.0 on 2023-06-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
